language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run stylelint
cache:
  directories:
  - $HOME/.npm
git:
  depth: 5
notifications:
  slack:
    rooms:
      - secure: jKCzXUh/W8bxqN0DxQnVz/R/t6fWX/ryW9zTYHLRBckpdP/QdBP13tPAJnpoP4ufX7MsKdsjxAt93EaC9ZRudXfZkJVaUT4s10TODPmd5re4/ayoyIUlCzPwkqPtL0FaSc1u+AnAJOdB3VVq1jF5io9+GvlTgaVkb/9bHb6aBPdr+uYaaPe1Ly88DcTFe69dT1diyObfU872ALAFVNrAB9CnmXntE0OFqmmKxhv+u4UbAL8Et2RKpe3hDklmFU4clJftIdYgHi74qGVuvx5moIkXVfxezX7mCtMtF2+bu+LeTTf7CaaeHIeHdgSudun3AS0X8QGOUedMTFYXjVB1wBrIN7MzRNIetcvQZeJmTjvDQ6wwtGhZWDnoWGnHhUqt15KRUcrfO2qI1xDojVLH2fQ17do70fpNcJAjgD+8XtYy4jfsoEVxfa691m2di6qL5ju4/6UEs/FebfRllTnhopo6C+O+wy19BZiA1KuioVklJHRNim+In9NbMgMrIne2Vj9l2OS429oXW0mse/KhxdICavOZG6GpWpEAKyhQojrTGBT9X5HBTn18hT7Broi2jG00EyrJRiajwJSj03x08zxIvpMu5m0NIGz/7t3d7JsEDn8ouY3NEyVQ3HeESvPUjCPCRdiQvQ1stepwKzlf7k32jNCkGgGMtlmZGqQQUbE=
    on_success: change
    on_failure: always
