language: node_js
before_install: 
  - nvm install $(cat .nvmrc)
  - nvm use
  - echo "//npm.pkg.github.com/:_authToken=$GITHUB_AUTH_TOKEN" > .npmrc
install:
- npm install
script:
- npm run lint:scss
cache:
  directories:
  - $HOME/.npm
git:
  depth: 5
notifications:
  slack:
    rooms:
      - secure: AsbzZOtkGPXxXreBi5vZ9Pn8lvC5z4BnxKDTJT2FRRlJYmT8Ry6gpLqrJWhdWTSDt7H+pvU+QQT+u3w8S+WOmlCKLSBUTmCQ5OMhnMLf8d34hk4T4JB58/OH+JHKfVlt9ZNw832fk5uadP3tQuMbkGcEpNMJTJb/Nq5oyoMb7rAfoXYLCF6SsQvXKWqR+bl1bZzykYK9QurKJFX0EjdN+jcZKVV3PEDMvgkWmnCq8R5yxUD2XHKYrRLAsyN1d3Gpb8iw2Edd2JSrLU4eTrbGXoBntZRvj3Y8hTmOAf95VIBypnaU1+AOKlSUFSgSeTrm3Cq0wi1GAhNvBtAIAePQKrPptDKOP3baGZmyIHZI1ma5SqY+mg8HY4c+YjAa7Fbwt83EjrfxXqg7jn9wDRhnyHO0wQ89EHZ2fngUFN9x1KrcYdjjuuLneEYzCZ2oSobfxJ3QExP24wGeD1Khx/XINENz9N9YrxgXFUMdzL3d1h8hjvCT2xMPOgqWeYw8RjkQ/XLp04vG9VFiy5Fz2Zcr95KfnZzJyA+JAj3hVIn0uUg3xYIHBs69mj0v+TmZ509HANiEUPjYmIjj3t7TUS/Woxp6HjsT3JyLBi28H3P8gE0PNoQ/3NslTjRjnbKLW1VJJk8LsTuiz5uk5watJgQeIGJvCiavEGwEHW96bCvibyo=
    on_success: change
    on_failure: always
